FROM golang:1.26-trixie AS build

COPY backend /app/backend
COPY json /app/json
COPY ddl /app/ddl

WORKDIR /app/backend
RUN go build -o /app/backend/main .

FROM debian:trixie-slim AS run
COPY --from=build /app/backend/main /app/backend/main
COPY backend/config.yaml /app/backend/config.yaml
COPY json /app/json
COPY ddl /app/ddl

WORKDIR /app/backend
CMD sleep 2 && /app/backend/main
