FROM golang:1.26-trixie AS build

COPY backend /app/backend
COPY ddl /app/ddl

WORKDIR /app/backend
RUN go build -o /app/backend/main .
RUN find . -name "*.go" -type f -delete

FROM debian:trixie-slim AS run
COPY --from=build /app/backend /app/backend
COPY ddl /app/ddl

WORKDIR /app/backend
CMD sleep 2 && /app/backend/main
